# Generated by Django 4.2.7 on 2024-02-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_revrubric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevRubric',
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={},
        ),
        migrations.AddField(
            model_name='rubric',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RevRubric',
            fields=[
                ('rubric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bboard.rubric')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
            bases=('bboard.rubric',),
        ),
    ]
