# Generated by Django 4.2.7 on 2024-02-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('testapp', '0002_mote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mote',
            new_name='Note',
        ),
    ]
